---
- name: Install prerequisite packages
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Set PostgreSQL environment variables
  become: true
  ansible.builtin.template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: '0644'
  notify: Restart postgresql

- name: Ensure PostgreSQL data directory exists
  become: true
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    owner: postgres
    group: postgres
    state: directory
    mode: '0700'

- name: Get passwd entry for postgres
  ansible.builtin.getent:
    database: passwd
    key: postgres

- name: Set home_dir and shell
  ansible.builtin.set_fact:
    postgres_home_dir: "{{ getent_passwd['postgres'][4] }}"

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: postgres_initdb_file

- name: Initialize PostgreSQL database
  when: not postgres_initdb_file.stat.exists
  block:
    - name: Create pwfile
      ansible.builtin.copy:
        dest: "{{ postgres_home_dir }}/pwfile"
        content: "{{ lookup('env', 'DB_PASS') }}"
        owner: postgres
        group: postgres
        mode: '0600'

    - name: Initialize Database
      become: true
      become_user: postgres
      ansible.builtin.command:
        cmd: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }} -A password --pwfile {{ postgres_home_dir }}/pwfile"
      args:
        creates: "{{ postgresql_data_dir }}/PG_VERSION"
      environment:
        LC_ALL: "{{ postgres_locale }}"

- name: Ensure pwfile is absent
  ansible.builtin.file:
    path: "{{ postgres_home_dir }}/pwfile"
    state: absent

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ postgresql_data_dir }}/server.key"
    group: postgres
    owner: postgres

- name: Generate an OpenSSL CSR with Subject information
  community.crypto.openssl_csr:
    path: "{{ postgresql_data_dir }}/server.csr"
    group: postgres
    owner: postgres
    privatekey_path: "{{ postgresql_data_dir }}/server.key"
    country_name: IT
    organization_name: Dev
    email_address: noreply@example.com
    common_name: "{{ ansible_fqdn | default(ansible_hostname) }}"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ postgresql_data_dir }}/server.crt"
    group: postgres
    owner: postgres
    privatekey_path: "{{ postgresql_data_dir }}/server.key"
    csr_path: "{{ postgresql_data_dir }}/server.csr"
    provider: selfsigned

- name: Setup postgres configuration files
  become: true
  become_user: postgres
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ postgresql_config_path }}/{{ item }}"
    owner: postgres
    group: postgres
    mode: '0644'
  loop:
    - pg_hba.conf
    - postgresql.conf
  notify: Restart postgresql

- name: Setup postgres systemd overide directory
  become: true
  ansible.builtin.file:
    path: "/etc/systemd/system/postgresql-{{ postgres_version }}.service.d"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Setup postgres systemd overides
  become: true
  ansible.builtin.template:
    src: override.conf.j2
    dest: "/etc/systemd/system/postgresql-{{ postgres_version }}.service.d/override.conf"
    owner: root
    group: root
    mode: '0644'

- name: Ensure PostgreSQL is started and enabled on boot
  become: true
  ansible.builtin.systemd:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: true

- name: Hold until Postgresql is up and running
  ansible.builtin.wait_for:
    port: "{{ postgres_port }}"
    timeout: 120
    sleep: 10

- name: Create user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    login_password: "{{ lookup('env', 'DB_PASS') }}"
    name: "{{ curr_user.username }}"
    password: "{{ curr_user.password }}"
    conn_limit: "-1"
  loop: "{{ database | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: curr_user
  when: curr_user.enabled | bool
  no_log: "{{ not debug }}"

- name: Create database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    login_password: "{{ lookup('env', 'DB_PASS') }}"
    name: "{{ curr_db.name }}"
    owner: "{{ curr_db.owner }}"
    encoding: UTF-8
    lc_collate: "{{ postgres_locale }}"
    lc_ctype: "{{ postgres_locale }}"
    template: template0
  loop: "{{ database | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: curr_db
  when: curr_db.enabled | bool
  no_log: "{{ not debug }}"

- name: Grant privs on db
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    login_password: "{{ lookup('env', 'DB_PASS') }}"
    database: "{{ curr_db.name }}"
    role: "{{ curr_db.owner }}"
    state: present
    privs: ALL
    type: database
  loop: "{{ database | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: curr_db
  when: curr_db.enabled | bool
  no_log: "{{ not debug }}"
